# This file was created by ChatGPT
FROM node:20-alpine AS build

WORKDIR /usr/src/app

COPY client/package*.json ./

RUN npm ci --omit=dev

COPY client/ .

RUN npm run build

FROM nginx:1.25-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/build /usr/share/nginx/html

EXPOSE 3000
