FROM node:20-alpine AS deps

WORKDIR /usr/src/app

RUN apk add --no-cache python3 make g++

COPY package*.json ./

RUN npm ci --omit=dev

FROM node:20-alpine AS runner

WORKDIR /usr/src/app

ENV NODE_ENV=production \
    DEV_MODE=production

COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .

EXPOSE 6060

CMD ["node", "server.js"]
