#!/usr/bin/env python3
# This file was generated by ChatGPT
"""
Plot container CPU and memory usage trends from docker-stats CSV exports.

Searches recursively for docker-stats-*.csv files under */results/raw next to this
script, then writes a PNG chart beside each CSV (in ../charts) showing CPU% and
memory% over time.
"""

from __future__ import annotations

import csv
from datetime import datetime
from pathlib import Path
from typing import List, Tuple

try:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.dates as mdates
    import matplotlib.pyplot as plt
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "matplotlib is required. Install it via `pip install matplotlib`."
    ) from exc

BASE_DIR = Path(__file__).resolve().parent
RAW_DIR_PATTERN = "*/results/raw"
CSV_PATTERN = "docker-stats-*.csv"


def parse_float(value: str | None) -> float | None:
    if value is None:
        return None
    try:
        return float(value.strip().rstrip("%"))
    except ValueError:
        return None


def parse_timestamp(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
            try:
                return datetime.strptime(value, fmt)
            except ValueError:
                continue
    return None


def read_usage_series(csv_path: Path) -> Tuple[List[datetime], List[float], List[float]]:
    timestamps: List[datetime] = []
    cpu_percentages: List[float] = []
    mem_percentages: List[float] = []

    with csv_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            ts = parse_timestamp(row.get("timestamp"))
            cpu = parse_float(row.get("cpu_percent"))
            mem = parse_float(row.get("mem_percent"))
            if ts is None or cpu is None or mem is None:
                continue
            timestamps.append(ts)
            cpu_percentages.append(max(min(cpu, 100.0), 0.0))
            mem_percentages.append(max(min(mem, 100.0), 0.0))

    ordered = sorted(zip(timestamps, cpu_percentages, mem_percentages), key=lambda x: x[0])
    if not ordered:
        return [], [], []
    t_values, cpu_values, mem_values = zip(*ordered)
    return list(t_values), list(cpu_values), list(mem_values)


def plot_usage(csv_path: Path, times: List[datetime], cpu: List[float], mem: List[float]) -> None:
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.plot(times, cpu, label="CPU (%)", color="#1f77b4", marker="o")
    ax.plot(times, mem, label="Memory (%)", color="#ff7f0e", marker="s")

    ax.set_xlabel("Time")
    ax.set_ylabel("Utilization (%)")
    ax.set_ylim(0, 100)

    ax.xaxis.set_major_formatter(mdates.DateFormatter("%H:%M:%S"))
    fig.autofmt_xdate()

    title = csv_path.stem.replace("docker-stats-", "").replace("_", " ").title()
    ax.set_title(title)
    ax.grid(True, linestyle=":", linewidth=0.5, alpha=0.7)
    ax.legend(loc="best")

    charts_dir = csv_path.parent.parent / "charts"
    charts_dir.mkdir(parents=True, exist_ok=True)
    output_path = charts_dir / f"{csv_path.stem}.png"
    fig.tight_layout()
    fig.savefig(output_path, dpi=150)
    plt.close(fig)
    print(f"Saved chart: {output_path}")


def find_csv_files(base_dir: Path) -> List[Path]:
    files: List[Path] = []
    for raw_dir in sorted(base_dir.glob(RAW_DIR_PATTERN)):
        if raw_dir.is_dir():
            files.extend(sorted(raw_dir.glob(CSV_PATTERN)))
    return files


def main() -> None:
    csv_files = find_csv_files(BASE_DIR)
    if not csv_files:
        print("No docker-stats CSV files found.")
        return
    for csv_file in csv_files:
        print(f"Processing {csv_file} ...")
        try:
            times, cpu, mem = read_usage_series(csv_file)
            if not times:
                print(f"  No valid data in {csv_file}")
                continue
            plot_usage(csv_file, times, cpu, mem)
        except Exception as exc:  # pragma: no cover
            print(f"  Failed to process {csv_file}: {exc}")


if __name__ == "__main__":
    main()
